gui:
  theme:
    activeBorderColor:
      - "#dc8a78"
      - bold
    inactiveBorderColor:
      - "#ccd0da"
    optionsTextColor:
      - "#4c4f69"
    selectedLineBgColor:
      - "#dce0e8"
    selectedRangeBgColor:
      - "#e6e9ef"
    cherryPickedCommitBgColor:
      - "#dd7878"
    cherryPickedCommitFgColor:
      - "#4c4f69"
    unstagedChangesColor:
      - "#d20f39"
    defaultFgColor:
      - "#4c4f69"
    searchingActiveBorderColor:
      - "#8839ef"
