gui:
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    optionsTextColor:
      - "#cdd6f4"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#45475a"
    cherryPickedCommitBgColor:
      - "#f38ba8"
    cherryPickedCommitFgColor:
      - "#cdd6f4"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#cba6f7"
